// src/vue/App.vue
<template>
  <div class="box">{{ name }}</div>
  <button @click="reverseName">反转</button>
</template>
<script>
import { ref } from 'vue';
export default {
  name: 'App',
  setup() {
    const name = ref('hello world');
    const reverseName = () => {
      name.value = name.value.split('').reverse().join('');
    };
    return { name, reverseName };
  },
};
</script>
<style lang="scss" scoped>
.box {
  color: red;
}
</style>

// src/react/App.jsx
import React, { Component } from 'react';
class App extends Component {
  constructor(props) {
    super(props),
      (this.state = {
        message: 'hello react',
      });
  }
  reverse() {
    this.setState(preState => ({
      message: preState.message.split('').reverse().join(''),
    }));
  }
  render() {
    const { message } = this.state;
    return (
      <div>
        <h2>{message}</h2>
        <button
          onClick={() => {
            this.reverse();
          }}
        >
          反转
        </button>
      </div>
    );
  }
}
export default App;
